<?php

  function sum_menu(){
    $items['sums'] = array (
    'title' => 'Calculate Sum',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sum_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
    $items['sum_success_page'] = array (
    'title' => 'Success',
    'page callback' => 'sum_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
    return $items;
  }

  function sum_form(){
    $form['left_number'] = array(
       '#title' => 'Left number',
       '#type' => 'textfield',
       '#description' => t('Please enter your starting number.'),
   );

   $form['right_number'] = array(
       '#title' => 'Right number',
       '#type' => 'textfield',
       '#description' => t('Please enter a number to add'),
   );

   $form['submit'] = array(
       '#type' => 'submit',
       '#value' => 'Calculate Sum',
   );

   return $form;
  }

  function sum_form_submit($form, &$form_state) {
    $first = $form_state['values']['left_number'];
    $second = $form_state['values']['right_number'];
    $sum = $first + $second;
    $_SESSION['sum_output'] = $sum;

    $form_state['redirect'] = 'sum_success_page';
}

function sum_success() {
  $answer = $_SESSION['sum_output'];
    return 'The result is ' . $answer;
}
