<?php

  function ping_pong_menu(){
    $items['pingpong'] = array (
    'title' => 'Make Pingpong',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ping_pong_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
    $items['ping_pong_success'] = array (
    'title' => 'Success',
    'page callback' => 'ping_pong_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
    return $items;
  }

  function ping_pong_form(){
    $form['number'] = array(
       '#title' => 'This number',
       '#type' => 'textfield',
       '#description' => t('Please enter yournumber.'),
   );
   $form['submit'] = array(
       '#type' => 'submit',
       '#value' => 'Make Ping Pong',
   );

   return $form;
  }

  function ping_pong_form_submit($form, &$form_state) {
    $number = $form_state['values']['number'];
    $output = array();
    for ($i=1; $i < $number ; $i++) {
      if ($i % 15 === 0 ) {
        array_push($output, "pingpong");
      } else if ($i % 5 === 0) {
        array_push($output, "pong");
      } else if ($i % 3 === 0) {
        array_push($output, "ping");
      } else {
        array_push($output, $i);
      }
    }
    $_SESSION['pingpong_output'] = $output;
    $form_state['redirect'] = 'ping_pong_success';
}

function ping_pong_success() {
  $answer = $_SESSION['pingpong_output'];
  $output = '<ul>';
  foreach ($answer as $pingpong) {
    $output = $output . '<li>' . $pingpong . '</li>' ;
  }
  $output = $output . '</ul>';
  return 'The result is: <br> ' . $output ;
}
